import { moderateScale, verticalScale } from '@constants/metrics';
import { Dimensions, StyleSheet } from 'react-native';

export const style = theme =>
  StyleSheet.create({
    container: { flex: 1 },
    backgroundImage: {
      position: 'absolute',
      left: -330,
      top: -328,
      width: 737,
      height: 657,
      opacity: 0.1,
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: verticalScale(24),
      marginHorizontal: moderateScale(16),
      marginBottom: verticalScale(8),
    },
    contentContainer: {
      padding: moderateScale(16),
    },
    mainCard: {
      backgroundColor: theme.colors.backgroundColor,
      borderRadius: moderateScale(10),
      padding: moderateScale(16),
      marginBottom: verticalScale(16),
    },
    companySection: {
      backgroundColor: theme.colors.backgroundColor,
      padding: moderateScale(16),
      borderRadius: moderateScale(10),
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    companyHeader: { flexDirection: 'row', alignItems: 'flex-start' },
    companyLogo: {
      width: verticalScale(75),
      height: verticalScale(75),
      borderRadius: moderateScale(8),
    },
    companyInfo: { flex: 1, marginLeft: moderateScale(16) },
    companyName: {
      fontSize: moderateScale(16),
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: verticalScale(4),
    },
    viewProfileText: {
      fontSize: moderateScale(13),
      color: theme.colors.primary,
      textDecorationLine: 'underline',
      marginBottom: verticalScale(4),
    },
    insuranceTypeText: {
      fontSize: moderateScale(14),
      color: theme.colors.description,
      fontWeight: '300',
      marginBottom: verticalScale(4),
    },
    priceButton: {
      backgroundColor: theme.colors.highlight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: verticalScale(12),
      borderRadius: moderateScale(5),
      marginTop: verticalScale(16),
    },
    priceButtonText: {
      fontSize: moderateScale(15),
      fontWeight: '600',
      color: theme.colors.text,
    },
    discountContainer: {
      backgroundColor: theme.colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      padding: verticalScale(12),
      marginTop: verticalScale(16),
      borderRadius: moderateScale(4),
    },
    checkIcon: {
      width: verticalScale(16),
      height: verticalScale(16),
      tintColor: theme.colors.primary,
    },
    discountText: {
      fontSize: moderateScale(11),
      marginLeft: moderateScale(8),
      flex: 1,
      color: theme.colors.text,
    },
    strikethrough: { textDecorationLine: 'line-through' },
    policyStatusContainer: {
      alignItems: 'flex-end',
      marginTop: verticalScale(8),
    },
    statusBadge: {
      paddingHorizontal: moderateScale(12),
      paddingVertical: verticalScale(4),
      borderRadius: moderateScale(4),
    },
    statusText: {
      fontSize: moderateScale(12),
      color: theme.colors.primary,
      fontWeight: '500',
    },
    indicativeText: { color: theme.colors.highlight },
    thirdPartyContainer: {
      backgroundColor: theme.colors.backgroundColor,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: moderateScale(3),
      padding: moderateScale(16),
      marginTop: verticalScale(16),
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: verticalScale(16),
    },
    infoIcon: { width: verticalScale(32), height: verticalScale(32) },
    infoContent: { marginLeft: moderateScale(12) },
    infoTitle: {
      fontSize: moderateScale(13),
      fontWeight: '600',
      color: theme.colors.primary,
    },
    infoValue: {
      fontSize: moderateScale(12),
      fontWeight: '300',
      color: theme.colors.description,
      textTransform: 'capitalize',
    },
    section: { marginTop: verticalScale(24) },
    sectionTitle: {
      fontSize: moderateScale(20),
      fontWeight: '600',
      color: theme.colors.primary,
      marginBottom: verticalScale(16),
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: verticalScale(16),
    },
    featureIcon: { width: verticalScale(35), height: verticalScale(28) },
    featureContent: { flex: 1, marginLeft: moderateScale(12) },
    featureHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    featureTitleContainer: { flex: 1 },
    featureTitle: {
      fontSize: moderateScale(14),
      fontWeight: '600',
      color: theme.colors.text,
    },
    featurePrice: {
      fontSize: moderateScale(12),
      fontWeight: '300',
      color: theme.colors.primary,
      marginTop: verticalScale(2),
    },
    featureDescription: {
      fontSize: moderateScale(12),
      fontWeight: '300',
      color: theme.colors.description,
      marginTop: verticalScale(8),
      lineHeight: verticalScale(18),
    },
    priceCard: {
      backgroundColor: theme.colors.backgroundColor,
      borderRadius: moderateScale(10),
      padding: moderateScale(15),
      marginBottom: verticalScale(16),
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    priceText: {
      fontSize: moderateScale(18),
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: verticalScale(4),
    },
    taxIncludedText: {
      fontSize: moderateScale(14),
      fontWeight: '300',
      color: theme.colors.text,
      marginBottom: verticalScale(16),
    },
    secureCheckoutText: {
      fontSize: moderateScale(14),
      color: theme.colors.primary,
      marginBottom: verticalScale(16),
    },
    buyPolicyButton: {
      backgroundColor: theme.colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: verticalScale(16),
      borderRadius: moderateScale(7),
      borderWidth: 1,
      borderColor: theme.colors.primary,
      gap: moderateScale(8),
    },
    buyPolicyButtonText: {
      fontSize: moderateScale(16),
      fontWeight: '500',
      color: theme.colors.backgroundColor,
    },
    addOnsCard: {
      backgroundColor: theme.colors.backgroundColor,
      borderRadius: moderateScale(10),
      padding: moderateScale(15),
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    addOnsTitle: {
      fontSize: moderateScale(20),
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: verticalScale(8),
    },
    addOnsSubtitle: {
      fontSize: moderateScale(16),
      fontWeight: '300',
      color: theme.colors.text,
      marginBottom: verticalScale(16),
    },
    addOnItem: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginVertical: verticalScale(10),
    },
    addOnInfo: { flex: 1, marginRight: moderateScale(16) },
    addOnName: {
      fontSize: moderateScale(14),
      fontWeight: '500',
      color: theme.colors.text,
      marginBottom: verticalScale(4),
    },
    addOnPrice: {
      fontSize: moderateScale(12),
      fontWeight: '300',
      color: theme.colors.primary,
      marginBottom: verticalScale(8),
    },
    addOnDescription: {
      fontSize: moderateScale(12),
      fontWeight: '300',
      color: theme.colors.description,
      lineHeight: verticalScale(16),
    },
  });
