export const COMPNAY_LIST = [
  {
    slug: 'alliance-insurance',
    fullLegalName: 'Alliance Insurance PJSC',
    tradingName: 'Alliance Insurance',
    shortName: 'AI',
    arabicName: 'شركة اللاينس للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Abu Dhabi',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.allianceinsurance.ae',
    contactNumber: '8002554262',
    logoUrl:
      'https://api.esanad.com/images/companies/2023-08/1692077913917-instruments-logo-13135389.png',
    apiId: '64c7b7f337ada531fa60ff2d',
  },
  {
    slug: 'united-fidelity-insurance',
    fullLegalName: 'United Fidelity Insurance Company PSC',
    tradingName: 'Fidelity United',
    shortName: 'FU',
    arabicName: 'شركة فيديليتي يونايتد للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.fidelityunited.ae',
    contactNumber: '800 842',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727531692800-rr.png',
    apiId: '64d6495bc4567ce1a5db7137',
  },
  {
    slug: 'adamjee-insurance',
    apiId: '64dcba696423880451e3ef1b',
    fullLegalName: 'Adamjee Insurance Company Limited',
    tradingName: 'Adamjee Insurance',
    shortName: 'AI',
    arabicName: 'أدمجي',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.adamjeeinsurance.ae',
    contactNumber: '600500242',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727532125210-III.png',
  },
  {
    slug: 'al-ain-al-ahlia-insurance',
    apiId: '64ddb4b15faa051f4ccc3ec3',
    fullLegalName: 'Al Ain Al Ahlia Insurance Company PSC',
    tradingName: 'Al Ain Al Ahlia Insurance',
    shortName: 'AAAAI',
    arabicName: 'العين الأهلية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.alaininsurance.com',
    contactNumber: '+97126119999',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727532167265-ZXCVBNM,.png',
  },
  {
    slug: 'abu-dhabi-national-takaful---matrix',
    apiId: '64ddb7965faa051f4ccc3ecf',
    fullLegalName: 'Abu Dhabi National Insurance Company PJSC',
    tradingName: 'ADNIC',
    shortName: 'ADNIC',
    arabicName: 'شركة أبوظبي الوطنية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.adnic.ae',
    contactNumber: '8008040',
    logoUrl:
      'https://api.esanad.com/images/companies/2023-09/1694377916630-Abu-Dhabi-National-Takaful.jpg',
  },
  {
    slug: 'dni',
    fullLegalName: 'Dubai National Insurance & Reinsurance Company PSC',
    tradingName: 'DNI',
    shortName: 'DNI',
    arabicName: 'شركة دبي الوطنية للتأمين وإعادة التأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.dni.ae',
    contactNumber: '600580000',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743587561985-DNI_Logo_.png',
    apiId: '64ddb9a55faa051f4ccc3ed9',
  },
  {
    slug: 'orient-insurance',
    fullLegalName: 'Orient Insurance PJSC',
    tradingName: 'Orient',
    shortName: 'O',
    arabicName: 'شركة أورينت للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.insuranceuae.com/',
    contactNumber: '800674368',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1745246257683-Screenshot_2025-04-21_183732.png',
    apiId: '64ddddf15faa051f4ccc3f07',
  },
  {
    slug: 'tokio-marine',
    apiId: '6505a93f4bb813f925c160b0',
    fullLegalName: 'Tokio Marine & Nichido Fire Insurance Co. Ltd.',
    tradingName: 'Tokio Marine',
    shortName: 'TM',
    arabicName: 'طوكيو مارين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.tmnf.ae',
    contactNumber: '600503030',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727532408437-QWERTYUIO.png',
  },
  {
    slug: 'arabia-insurance',
    apiId: '651ae4fb893162d25a866913',
    fullLegalName: 'Arabia Insurance Company s.a.l. (UAE Branch)',
    tradingName: 'Arabia Insurance',
    shortName: 'AI',
    arabicName: 'شركة العربية للتأمين – فرع الإمارات',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://uae.arabiainsurance.com',
    contactNumber: '80024223',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727421601539-Arabia.png',
  },
  {
    slug: 'insurance-house',
    fullLegalName: 'Insurance House PJSC',
    tradingName: 'Insurance House',
    shortName: 'IH',
    arabicName: 'شركة دار التأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.insurancehouse.ae',
    contactNumber: '600511112',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743588661710-Insurance_house_logo_2.jpeg',
    apiId: '652e60cbe60ef36fe0570aa1',
  },
  {
    slug: 'rak-insurance',
    apiId: '65659d6985bcd83461e29cf0',
    fullLegalName: 'Ras Al Khaimah National Insurance Company PSC',
    tradingName: 'RAK Insurance',
    shortName: 'RI',
    arabicName: 'شركة رأس الخيمة الوطنية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Ras Al Khaimah',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.rakinsurance.com',
    contactNumber: '8007254',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727420552971-RAK_LOGO.jpg',
  },
  {
    slug: 'adntc',
    fullLegalName: 'Abu Dhabi National Insurance Company PJSC',
    tradingName: 'ADNIC',
    shortName: 'ADNIC',
    arabicName: 'شركة أبوظبي الوطنية للتأمين',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.adnic.ae',
    contactNumber: '8008040',
    logoUrl:
      'https://api.esanad.com/images/companies/2023-12/1702387358109-1694377916630-Abu-Dhabi-National-Takaful.jpg',
    apiId: '65785e9ee4d3ef6e44c0e1f6',
  },
  {
    slug: 'salama-insurance',
    apiId: '65c9bcee58faa72fdc857a41',
    fullLegalName: 'Islamic Arab Insurance Company PJSC',
    tradingName: 'SALAMA',
    shortName: 'SALAMA',
    arabicName: 'الشركة الإسلامية العربية للتأمين',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.salama.ae',
    contactNumber: '80072526',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727531534005-QQ.png',
  },
  {
    slug: 'qic',
    apiId: '660662722fc88d4cf3ec1815',
    fullLegalName: 'Qatar Insurance Company Q.S.P.C. (UAE Branch)',
    tradingName: 'QIC',
    shortName: 'QIC',
    arabicName: 'شركة قطر للتأمين – فرع الإمارات',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.qicuae.com',
    contactNumber: '8004742',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743588423369-QIC_Logo_2.png',
  },
  {
    slug: 'al-ittihad-al-watani',
    apiId: '66611ba20d0832ee557236d1',
    fullLegalName:
      'Al Ittihad Al Watani (General Insurance Society for the Near East)',
    tradingName: 'Al Ittihad Al Watani',
    shortName: 'AIAW',
    arabicName: 'شركة الاتحاد الوطني للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.alittihadalwatani.com',
    contactNumber: '+97142106800',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743588260910-Ittihad.png',
  },
  {
    slug: 'liva-insurance',
    apiId: '69833d6a24f9df893d276a57',
    fullLegalName: 'Liva Insurance (formerly NLGI / RSA Middle East)',
    tradingName: 'Liva Insurance',
    shortName: 'LIVA',
    arabicName: 'ليفا للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.livainsurance.ae',
    contactNumber: '800774',
    logoUrl:
      'https://api.esanad.com/images/companies/2026-02/1770208618963-images.png',
  },
  {
    slug: 'orient-takaful',
    apiId: '66611ba20d0832ee557236d7',
    fullLegalName: 'Orient Takaful PJSC',
    tradingName: 'Orient Takaful',
    shortName: 'OT',
    arabicName: 'أورينت تكافل',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.orienttakaful.com',
    contactNumber: '+97146017500',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727422031265-Orient.png',
  },
  {
    slug: 'takaful-emarat',
    fullLegalName: 'Takaful Emarat Insurance PSC',
    tradingName: 'Takaful Emarat',
    shortName: 'TE',
    arabicName: 'تكافل الإمارات للتأمين',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.takaful.ae',
    contactNumber: '600522550',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-05/1714559669590-TakafulEmirate.png',
    apiId: '66611ba20d0832ee557236d9',
  },
  {
    slug: 'medgulf',
    apiId: '66696c4000f52745fce5c930',
    fullLegalName: 'Mediterranean & Gulf Insurance and Reinsurance Company',
    tradingName: 'MEDGULF',
    shortName: 'MEDGULF',
    arabicName: 'ميدغلف',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.medgulf.ae',
    contactNumber: '+97143738888',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-06/1718185024590-Medgulf-logo.png',
  },
  {
    slug: 'union-insurance',
    apiId: '66b22803e67225ea192f5014',
    fullLegalName: 'Union Insurance Company PJSC',
    tradingName: 'Union Insurance',
    shortName: 'UI',
    arabicName: 'شركة الاتحاد للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.unioninsurance.ae',
    contactNumber: '600508181',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743587080440-Union_Logo.png',
  },
  {
    slug: 'dubai-insurance',
    apiId: '66b229cae67225ea192f581b',
    fullLegalName: 'Dubai Insurance Company PSC',
    tradingName: 'DIC',
    shortName: 'DIC',
    arabicName: 'شركة دبي للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.dubins.ae',
    contactNumber: '800382467',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727420671288-DIC.jpg',
  },
  {
    slug: 'damana-insurance',
    apiId: '66b22e5d0c721f8f0d2781b6',
    fullLegalName: 'DAMANA Insurance Company PSC',
    tradingName: 'DAMANA (formerly SAICO)',
    shortName: 'DFS',
    arabicName: 'ضمانة للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.damana.com',
    contactNumber: '+97142752400',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743584671433-Damana_Logo.jpeg',
  },
  {
    slug: 'jordan-insurance',
    apiId: '66b22ef50c721f8f0d278257',
    fullLegalName: 'Jordan Insurance',
    tradingName: 'Jordan Insurance',
    shortName: 'JI',
    arabicName: '',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Abu Dhabi',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: '',
    contactNumber: '',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743584291957-Jordan_Insurance_Logo.jpeg',
  },
  {
    slug: 'methaq-takaful-insurance',
    apiId: '66cebc334e990af2954b3843',
    fullLegalName: 'Methaq Takaful Insurance PSC',
    tradingName: 'Methaq',
    shortName: 'M',
    arabicName: 'ميثاق للتأمين التكافلي',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'ABU DHABI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.methaq.ae',
    contactNumber: '600565695',
    logoUrl:
      'https://api.esanad.com/images/companies/2024-09/1727531612456-WWW.png',
  },
  {
    slug: 'asnic-al-sagr-insurance',
    apiId: '64d648cbc4567ce1a5db712e',
    fullLegalName: 'Al Sagr National Insurance Company PSC',
    tradingName: 'ASNIC',
    shortName: 'ASNIC',
    arabicName: 'شركة الصقر الوطنية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.alsagrins.ae',
    contactNumber: '+97147028500',
    logoUrl:
      'https://api.esanad.com/images/companies/2023-08/1692077729891-alsaqrinsurance.png',
  },
  {
    slug: 'abnic-al-buhaira-insurance',
    apiId: '6710c0adc03576ad8180d26c',
    fullLegalName: 'Al Buhaira National Insurance Company PSC',
    tradingName: 'ABNIC',
    shortName: 'ABNIC',
    arabicName: 'شركة البحيرة الوطنية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Sharjah',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.albuhaira.com',
    contactNumber: '+97165174444',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743584188161-Buhaira_Logo.jpeg',
  },
  {
    slug: 'afnic-fujairah-insurance',
    apiId: '67457337d1a47242e835ce87',
    fullLegalName: 'Al Fujairah National Insurance Company PSC',
    tradingName: 'AFNIC',
    shortName: 'AFNIC',
    arabicName: 'شركة الفجيرة الوطنية للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'DUBAI',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.afnic.ae',
    contactNumber: '+97192233355',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743583393378-Fujaira_Logo.jpeg',
  },
  {
    slug: 'watania-takaful',
    fullLegalName: 'Watania International Holding PJSC (Watania Takaful)',
    tradingName: 'Watania',
    shortName: 'W',
    arabicName: 'الوطنية للتكافل',
    insuranceModel: 'Takaful',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.watania.ae',
    contactNumber: '8009282642',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-08/1754378841275-watania-takaful-insurance.png',
    apiId: '6891b259f4ae7925cedb91a6',
  },
  {
    slug: 'nlgi',
    apiId: '66611ba20d0832ee557236d3',
    fullLegalName: 'National Life & General Insurance Company',
    tradingName: 'National Life & General Insurance Company',
    shortName: 'NLGI',
    arabicName: 'ليفا للتأمين',
    insuranceModel: 'Conventional',
    businessClass: 'General',
    headquarters: 'Dubai',
    isEsanadPartner: true,
    availableOnEsanad: true,
    website: 'https://www.nlgi.ae',
    contactNumber: '800774',
    logoUrl:
      'https://api.esanad.com/images/companies/2025-04/1743587865609-NLGI_Logo.jpeg',
  },
];
